# Generated by Django 4.1.1 on 2022-10-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_listing_num_bathrooms_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Listing", new_name="Gallery",),
    ]
