# Generated by Django 4.1.1 on 2022-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery360",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                ("title", models.CharField(max_length=80)),
                ("summary", models.CharField(max_length=100)),
            ],
        ),
    ]
