# Generated by Django 4.1.1 on 2022-10-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_gallery360"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery360",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
